// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIg7Fh0AbYEcuGaSFfRFjg4Usiliug6qQ',
    appId: '1:1061691837491:web:ed97709306c883c0532746',
    messagingSenderId: '1061691837491',
    projectId: 'wekend-masti',
    authDomain: 'wekend-masti.firebaseapp.com',
    storageBucket: 'wekend-masti.firebasestorage.app',
    measurementId: 'G-M76C32D292',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPpcQxZ10KsC5o1PG5oBxQIN3faQ5zF8U',
    appId: '1:1061691837491:android:3ada78d3e125ecf6532746',
    messagingSenderId: '1061691837491',
    projectId: 'wekend-masti',
    storageBucket: 'wekend-masti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQJYVS7pQ9CdxAZ-PVo_sGF_gwIAltAt8',
    appId: '1:1061691837491:ios:7d454a89ed94e572532746',
    messagingSenderId: '1061691837491',
    projectId: 'wekend-masti',
    storageBucket: 'wekend-masti.firebasestorage.app',
    iosBundleId: 'com.example.wekendMasti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQJYVS7pQ9CdxAZ-PVo_sGF_gwIAltAt8',
    appId: '1:1061691837491:ios:7d454a89ed94e572532746',
    messagingSenderId: '1061691837491',
    projectId: 'wekend-masti',
    storageBucket: 'wekend-masti.firebasestorage.app',
    iosBundleId: 'com.example.wekendMasti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIg7Fh0AbYEcuGaSFfRFjg4Usiliug6qQ',
    appId: '1:1061691837491:web:36b2912ac4c5e8e1532746',
    messagingSenderId: '1061691837491',
    projectId: 'wekend-masti',
    authDomain: 'wekend-masti.firebaseapp.com',
    storageBucket: 'wekend-masti.firebasestorage.app',
    measurementId: 'G-1VFW227CF5',
  );
}
